---
- name: download
  get_url: url="{{ btsync_url[ansible_architecture] }}"
           dest=/tmp/btsync.tar.gz
  register: download

- name: extract
  command: tar xvzf /tmp/btsync.tar.gz -C /tmp
  when: download | changed

- name: copy btsync to /usr/local/bin
  command: cp /tmp/btsync /usr/local/bin/
  notify: start btsync
  when: download | changed

- name: install service
  template: src=btsync dest=/etc/init.d/btsync mode=755

- name: activate service
  service: name=btsync enabled=yes

- name: create group {{ btsync_user }}
  group: name={{ btsync_user }} state=present

- name: create user {{ btsync_user }}
  user: name={{ btsync_user }} shell=/bin/sh groups={{ btsync_user }} state=present

- name: create .sync directory
  file: path=/home/{{ btsync_user }}/.sync owner={{ btsync_user }} group={{ btsync_user }} mode=0700 state=directory

- name: copy config
  template: src=config.json dest=/home/{{ btsync_user }}/.sync/ owner={{ btsync_user }} group={{ btsync_user }} mode=700
  notify: restart btsync

- name: create folders
  file: path={{ item.path }} recurse=yes state=directory owner={{ btsync_user }} group={{ btsync_user }} mode=700
  with_items: btsync_shared_folders
  when: btsync_shared_folders is defined

- name: Fix .SyncIgnore
  lineinfile: dest={{ item.path }}/.SyncIgnore regexp='^lost\+found' line='lost+found' insertafter='OS generated files'
  with_items: btsync_shared_folders
  when: btsync_shared_folders is defined
